# categories = {
#         "IT služby": ["software", "vývoj aplikací", "programování", "IT řešení"],
#         "Stavebnictví": ["stavba", "rekonstrukce", "izolace", "zateplení"],
#         "Gastronomie": ["restaurace", "jídelna", "kavárna", "pizza", "kuchyně"],
#         "Automotive": ["autoservis", "vozidla", "opravy aut", "pneuservis"],
#         "Vzdělávání": ["školení", "kurzy", "výuka", "seminář", "učebna"],
#         "Zdravotnictví": ["lékař", "klinik", "zubař", "ordinace"],
#         "Bankovnictví": ["banka", "úvěr", "hypotéka", "půjčka"],
#         "Pojišťovnictví": ["pojištění", "pojistka", "asistence", "úrazové"],
#         "Maloobchod": ["prodejna", "obchod", "kamenný obchod", "zákazník"],
#         "Velkoobchod": ["distributor", "sklad", "dodavatel", "velkoobchod"],
#         "E-shopy": ["e-shop", "online obchod", "nákup", "košík"],
#         "Doprava": ["přeprava", "logistika", "kurýr", "dopravce"],
#         "Skladování": ["sklad", "logistické centrum", "uskladnění"],
#         "Zemědělství": ["farma", "pěstování", "zemědělské", "živočišná výroba"],
#         "Lesnictví": ["těžba dřeva", "pěstování lesa", "lesní správa"],
#         "Potravinářství": ["výroba potravin", "pekárna", "maso", "mlékárna"],
#         "Energetika": ["elektřina", "energie", "plyn", "solární"],
#         "Těžba a dobývání": ["těžba", "uhlí", "ruda", "lomy"],
#         "Vodní hospodářství": ["vodovod", "kanalizace", "úpravna vody"],
#         "Chemický průmysl": ["chemikálie", "barvy", "plasty", "hnojiva"],
#         "Textilní průmysl": ["textil", "oblečení", "oděvy", "šicí dílna"],
#         "Výroba nábytku": ["nábytek", "truhlářství", "skříň", "postel"],
#         "Výroba strojů": ["strojírenství", "výrobní linky", "soustruh", "obrábění"],
#         "Výroba elektroniky": ["elektronika", "senzor", "deska", "mikroprocesor"],
#         "Papírenství": ["papír", "tisk", "obálka", "lepenka"],
#         "Tisk a polygrafie": ["tiskárna", "kniha", "leták", "grafika"],
#         "Reklama a marketing": ["reklama", "kampaně", "branding", "SEO"],
#         "Nemovitosti": ["realitní kancelář", "prodej bytu", "pronájem", "developing"],
#         "Právo a advokacie": ["advokát", "právník", "soud", "smlouvy"],
#         "Účetnictví a daně": ["účetní", "daňové přiznání", "faktury"],
#         "Konzultace a poradenství": ["poradenství", "konzultace", "strategie"],
#         "Kreativní profese": ["fotograf", "designér", "grafik", "video"],
#         "Kultura a umění": ["galerie", "divadlo", "výstava", "hudebník"],
#         "Sport a fitness": ["fitko", "sportoviště", "trenér", "cvičení"],
#         "Cestovní ruch": ["hotel", "ubytování", "dovolená", "turistika"],
#         "Cestovní kanceláře": ["zájezd", "letenky", "průvodce"],
#         "Veřejná správa": ["město", "obec", "úřad", "magistrát"],
#         "Sociální služby": ["domov důchodců", "pečovatel", "sociální pracovník"],
#         "Neziskové organizace": ["spolek", "neziskovka", "charita"],
#         "Bezpečnostní služby": ["ostraha", "bezpečnostní agentura", "kamerový systém"],
#         "Úklidové služby": ["úklid", "čištění", "hygiena"],
#         "Kadeřnictví a kosmetika": ["kadeřník", "kosmetika", "manikúra"],
#         "Osobní služby": ["masáž", "wellness", "lázně", "terapie"],
#         "Domácí opravy a servis": ["instalatér", "elektrikář", "opravář"],
#         "Pronájem techniky": ["půjčovna", "stroj", "nástroj", "zařízení"],
#         "Zábavní průmysl": ["kino", "festival", "zábava", "event"],
#         "Žurnalistika a média": ["noviny", "časopis", "redakce", "reportér"],
#         "Telekomunikace": ["mobil", "internet", "síť", "operátor"],
#         "Výzkum a vývoj": ["laboratoř", "výzkum", "testování", "inovace"]
#     }

categories = {
"IT služby": ["software", "vývoj aplikací", "programování", "IT řešení", "webové stránky", "kódování", "správa IT", "informační systémy", "IT podpora", "sítě"],
"Stavebnictví": ["stavba", "rekonstrukce", "izolace", "zateplení", "stavební firma", "zemní práce", "hrubá stavba", "inženýrské sítě", "stavební dozor", "projektová dokumentace"],
"Gastronomie": ["restaurace", "jídelna", "kavárna", "pizza", "kuchyně", "gastronomické služby", "bistro", "bufet", "stravování", "pivnice"],
"Automotive": ["autoservis", "vozidla", "opravy aut", "pneuservis", "diagnostika vozidel", "automobilový průmysl", "prodej aut", "technická kontrola", "autosalon", "autodíly"],
"Vzdělávání": ["školení", "kurzy", "výuka", "seminář", "učebna", "jazykové kurzy", "e-learning", "vzdělávací středisko", "pedagog", "lektor"],
"Zdravotnictví": ["lékař", "klinik", "zubař", "ordinace", "ambulance", "praktický lékař", "gynekologie", "fyzioterapie", "zdravotní péče", "poliklinika"],
"Bankovnictví": ["banka", "úvěr", "hypotéka", "půjčka", "běžný účet", "platební karta", "spoření", "finanční instituce", "bankovní služby", "Komerční banka"],
"Pojišťovnictví": ["pojištění", "pojistka", "asistence", "úrazové", "životní pojištění", "cestovní pojištění", "pojišťovna", "pojistné smlouvy", "riziko", "škodní událost"],
"Maloobchod": ["prodejna", "obchod", "kamenný obchod", "zákazník", "maloobchodní síť", "kasa", "prodej zboží", "retail", "pokladna", "nákupní centrum"],
"Velkoobchod": ["distributor", "sklad", "dodavatel", "velkoobchod", "objednávky", "logistika", "nákup", "zásobování", "odběratel", "b2b prodej"],
"E-shopy": ["e-shop", "online obchod", "nákup", "košík", "platební brána", "doručení", "zásilkovna", "eshop platforma", "produktové karty", "internetový prodej"],
"Doprava": ["přeprava", "logistika", "kurýr", "dopravce", "nákladní doprava", "expedice", "logistické centrum", "doručení", "přepravní služba", "flotila"],
"Skladování": ["sklad", "logistické centrum", "uskladnění", "logistika", "regály", "skladové hospodářství", "logistické služby", "skladník", "skladové prostory", "distribuce"],
"Zemědělství": ["farma", "pěstování", "zemědělské", "živočišná výroba", "hnojiva", "rostlinná výroba", "zemědělské stroje", "chov zvířat", "agropodnik", "sklizeň"],
"Lesnictví": ["těžba dřeva", "pěstování lesa", "lesní správa", "lesnictví", "hospodaření s lesy", "lesní technika", "obnova lesa", "sadba stromů", "ochrana lesa", "dřeviny"],
"Potravinářství": ["výroba potravin", "pekárna", "maso", "mlékárna", "potravinářský průmysl", "balení potravin", "mléčné výrobky", "pečivo", "potravinářská výroba", "cukrovinky"],
"Energetika": ["elektřina", "energie", "plyn", "solární", "obnovitelné zdroje", "energetická efektivita", "distribuce elektřiny", "fotovoltaika", "výroba energie", "energie z biomasy"],
"Těžba a dobývání": ["těžba", "uhlí", "ruda", "lomy", "hornictví", "doly", "dobývání surovin", "těžební činnost", "geologie", "vrtné práce"],
"Vodní hospodářství": ["vodovod", "kanalizace", "úpravna vody", "vodní zdroje", "vodohospodářské služby", "čištění odpadních vod", "vodní sítě", "vodohospodářství", "pitná voda", "monitoring vody"],
"Chemický průmysl": ["chemikálie", "barvy", "plasty", "hnojiva", "průmyslová chemie", "laboratoř", "chemický průmysl", "rozpouštědla"],
"Textilní průmysl": ["textil", "oblečení", "oděvy", "šicí dílna", "švadlena", "móda", "oděvní výroba"],
"Výroba nábytku": ["nábytek", "truhlářství", "skříň", "postel", "interiéry", "čalounění", "kuchyňské linky"],
"Výroba strojů": ["strojírenství", "výrobní linky", "soustruh", "obrábění", "svařování", "technologické celky"],
"Výroba elektroniky": ["elektronika", "senzor", "deska", "mikroprocesor", "čipy", "PCB", "řídicí jednotka"],
"Papírenství": ["papír", "tisk", "obálka", "lepenka", "celulóza", "papírenský průmysl"],
"Tisk a polygrafie": ["tiskárna", "kniha", "leták", "grafika", "brožura", "plakát", "digitální tisk"],
"Reklama a marketing": ["reklama", "kampaně", "branding", "SEO", "marketing", "reklamní agentura", "PPC", "sociální sítě"],
"Nemovitosti": ["realitní kancelář", "prodej bytu", "pronájem", "developing", "nemovitost", "rezidence", "developerský projekt"],
"Právo a advokacie": ["advokát", "právník", "soud", "smlouvy", "právní služby", "zákon", "právní poradenství"],
"Účetnictví a daně": ["účetní", "daňové přiznání", "faktury", "účetnictví", "mzdové účetnictví", "daňová evidence"],
"Konzultace a poradenství": ["poradenství", "konzultace", "strategie", "management", "analýza", "business plán"],
"Kreativní profese": ["fotograf", "designér", "grafik", "video", "kamera", "tvorba obsahu", "kreativní studio"],
"Kultura a umění": ["galerie", "divadlo", "výstava", "hudebník", "umělec", "koncert", "kulturní centrum"],
"Sport a fitness": ["fitko", "sportoviště", "trenér", "cvičení", "fitness", "posilovna", "sportovní aktivity"],
"Cestovní ruch": ["hotel", "ubytování", "dovolená", "turistika", "penzion", "apartmán", "ubytovací služby"],
"Cestovní kanceláře": ["zájezd", "letenky", "průvodce", "dovolená", "cestovka", "cestovní agentura"],
"Veřejná správa": ["město", "obec", "úřad", "magistrát", "úředník", "samospráva", "veřejné služby"],
"Sociální služby": ["domov důchodců", "pečovatel", "sociální pracovník", "sociální péče", "terénní služby"],
"Neziskové organizace": ["spolek", "neziskovka", "charita", "fundraising", "dobrovolnictví"],
"Bezpečnostní služby": ["ostraha", "bezpečnostní agentura", "kamerový systém", "bezpečnostní dohled", "alarm"],
"Úklidové služby": ["úklid", "čištění", "hygiena", "úklidová firma", "úklidové práce"],
"Kadeřnictví a kosmetika": ["kadeřník", "kosmetika", "manikúra", "pedikúra", "vizážista", "beauty studio"],
"Osobní služby": ["masáž", "wellness", "lázně", "terapie", "fyzioterapie", "relaxace", "rehabilitace"],
"Domácí opravy a servis": ["instalatér", "elektrikář", "opravář", "řemeslník", "servis domácností"],
"Pronájem techniky": ["půjčovna", "stroj", "nástroj", "zařízení", "technika", "pronájem vybavení"],
"Zábavní průmysl": ["kino", "festival", "zábava", "event", "kulturní akce", "hudební festival", "divadlo"],
"Žurnalistika a média": ["noviny", "časopis", "redakce", "reportér", "zpravodajství", "publicistika"],
"Telekomunikace": ["mobil", "internet", "síť", "operátor", "telekomunikační služby", "datové připojení"],
"Výzkum a vývoj": ["laboratoř", "výzkum", "testování", "inovace", "věda", "vývoj produktů"]
}