categories = {
        "IT služby": ["software", "vývoj aplikací", "programování", "IT řešení"],
        "Stavebnictví": ["stavba", "rekonstrukce", "izolace", "zateplení"],
        "Gastronomie": ["restaurace", "jídelna", "kavárna", "pizza", "kuchyně"],
        "Automotive": ["autoservis", "vozidla", "opravy aut", "pneuservis"],
        "Vzdělávání": ["školení", "kurzy", "výuka", "seminář", "učebna"],
        "Zdravotnictví": ["lékař", "klinik", "zubař", "ordinace"],
        "Bankovnictví": ["banka", "úvěr", "hypotéka", "půjčka"],
        "Pojišťovnictví": ["pojištění", "pojistka", "asistence", "úrazové"],
        "Maloobchod": ["prodejna", "obchod", "kamenný obchod", "zákazník"],
        "Velkoobchod": ["distributor", "sklad", "dodavatel", "velkoobchod"],
        "E-shopy": ["e-shop", "online obchod", "nákup", "košík"],
        "Doprava": ["přeprava", "logistika", "kurýr", "dopravce"],
        "Skladování": ["sklad", "logistické centrum", "uskladnění"],
        "Zemědělství": ["farma", "pěstování", "zemědělské", "živočišná výroba"],
        "Lesnictví": ["těžba dřeva", "pěstování lesa", "lesní správa"],
        "Potravinářství": ["výroba potravin", "pekárna", "maso", "mlékárna"],
        "Energetika": ["elektřina", "energie", "plyn", "solární"],
        "Těžba a dobývání": ["těžba", "uhlí", "ruda", "lomy"],
        "Vodní hospodářství": ["vodovod", "kanalizace", "úpravna vody"],
        "Chemický průmysl": ["chemikálie", "barvy", "plasty", "hnojiva"],
        "Textilní průmysl": ["textil", "oblečení", "oděvy", "šicí dílna"],
        "Výroba nábytku": ["nábytek", "truhlářství", "skříň", "postel"],
        "Výroba strojů": ["strojírenství", "výrobní linky", "soustruh", "obrábění"],
        "Výroba elektroniky": ["elektronika", "senzor", "deska", "mikroprocesor"],
        "Papírenství": ["papír", "tisk", "obálka", "lepenka"],
        "Tisk a polygrafie": ["tiskárna", "kniha", "leták", "grafika"],
        "Reklama a marketing": ["reklama", "kampaně", "branding", "SEO"],
        "Nemovitosti": ["realitní kancelář", "prodej bytu", "pronájem", "developing"],
        "Právo a advokacie": ["advokát", "právník", "soud", "smlouvy"],
        "Účetnictví a daně": ["účetní", "daňové přiznání", "faktury"],
        "Konzultace a poradenství": ["poradenství", "konzultace", "strategie"],
        "Kreativní profese": ["fotograf", "designér", "grafik", "video"],
        "Kultura a umění": ["galerie", "divadlo", "výstava", "hudebník"],
        "Sport a fitness": ["fitko", "sportoviště", "trenér", "cvičení"],
        "Cestovní ruch": ["hotel", "ubytování", "dovolená", "turistika"],
        "Cestovní kanceláře": ["zájezd", "letenky", "průvodce"],
        "Veřejná správa": ["město", "obec", "úřad", "magistrát"],
        "Sociální služby": ["domov důchodců", "pečovatel", "sociální pracovník"],
        "Neziskové organizace": ["spolek", "neziskovka", "charita"],
        "Bezpečnostní služby": ["ostraha", "bezpečnostní agentura", "kamerový systém"],
        "Úklidové služby": ["úklid", "čištění", "hygiena"],
        "Kadeřnictví a kosmetika": ["kadeřník", "kosmetika", "manikúra"],
        "Osobní služby": ["masáž", "wellness", "lázně", "terapie"],
        "Domácí opravy a servis": ["instalatér", "elektrikář", "opravář"],
        "Pronájem techniky": ["půjčovna", "stroj", "nástroj", "zařízení"],
        "Zábavní průmysl": ["kino", "festival", "zábava", "event"],
        "Žurnalistika a média": ["noviny", "časopis", "redakce", "reportér"],
        "Telekomunikace": ["mobil", "internet", "síť", "operátor"],
        "Výzkum a vývoj": ["laboratoř", "výzkum", "testování", "inovace"]
    }